### ISSUE TITLE
apcupsd service not shown on web UI after install + reboot

### ISSUE THREAD

**Issue by dbrandesky** [Gibbon99/apcupsd#2]
I installed apcupsd on my system using pkg install, copied over the files from this repo, then ran the +POST_INSTALL script. I can see /usr/local/etc/inc/plugins.inc.d/apcupsd.inc exists, and it has the same permissions as any other .inc file, however it isn't showing up in the web UI under services.

I actually rebooted the entire opnsense box, but the service still didn't appear. I also manually restarted configd; no change. I have confirmed that the apcupsd service is running (configured via monit as shown in the instructions), and in fact I actually manually set up apcupsd.conf to my needs so my client devices could connect to the UPS as needed.

What else should I check to figure out why the service isn't appearing on the web UI? I'm very familiar with Linux troubleshooting but BSD is new to me.

**Comment by mrzaz** [comment]
I think i may have found the issue.  All the files in the repo was saved using Windows 0D0A line endings and not Unix 0A which causes bsd not to work properly. I will talk with David and make some adjustments.
I had same issue as you but now it works after I adjusted this in my install.
//Danne (MrZaZ)

![image](https://user-images.githubusercontent.com/9613777/130317059-d7e4691d-744c-4cfa-9b48-b873fc2b00ab.png)

**Comment by mrzaz** [comment]
> 
> 
> I installed apcupsd on my system using pkg install, copied over the files from this repo, then ran the +POST_INSTALL script. I can see /usr/local/etc/inc/plugins.inc.d/apcupsd.inc exists, and it has the same permissions as any other .inc file, however it isn't showing up in the web UI under services.
> 
> I actually rebooted the entire opnsense box, but the service still didn't appear. I also manually restarted configd; no change. I have confirmed that the apcupsd service is running (configured via monit as shown in the instructions), and in fact I actually manually set up apcupsd.conf to my needs so my client devices could connect to the UPS as needed.
> 
> What else should I check to figure out why the service isn't appearing on the web UI? I'm very familiar with Linux troubleshooting but BSD is new to me.

Could you please checkout a new fresh from the master branch which contains the latest commit I did today and try again
and let me know if it works.
If it does not work and you have access to SSH to opnsense you could try the following commands:

configctl apcupsd getNisStatus
configctl apcupsd getServiceStatus
/usr/sbin/service apcupsd status
/usr/local/sbin/apcaccess
/usr/local/opnsense/scripts/OPNsense/Apcupsd/getNisStatus.py

service configd restart
configctl apcupsd getNisStatus

Also do a small test to check if files is Windows CRLF or Unix LF:

OK
root@OPNsense:/home/mrzaz # file /usr/local/opnsense/scripts/OPNsense/Apcupsd/getNisStatus.py
/usr/local/opnsense/scripts/OPNsense/Apcupsd/getNisStatus.py: Python script, ASCII text executable

NOK
root@OPNsense:/home/mrzaz # file /usr/local/opnsense/scripts/OPNsense/Apcupsd/getNisStatus.py
getNisStatus.py: Python script, ASCII text executable, with CRLF line terminators

Let me know if this sorted out your problem so we could close this issue.

//Dan L (mrzaz)

**Comment by mrzaz** [comment]
I have just discovered that the problem is introduced by the GitHub Desktop Windows client that checks out the textfiles to CRLF (0x0D0A) linefeed regardless of the source line endings which will cause issues if you use these directly to OPNSENSE.

I have now abandoned the GitHub Client in Windows and went for GitExtensions + Git instead (also testing out GitKraken) where I could configured how it should behave.

If you are on Windows, please try another GitHub client to make sure that the it don't convert LF to CRLF during checkout.
Here are a few other GitHub clients.   https://git-scm.com/download/gui/windows

![image](https://user-images.githubusercontent.com/9613777/130363266-8e9f0580-9b75-4fe0-bcfb-f67a1fd91c67.png)

Pleas let me know if this solved your problem so we could close this issue.

//Danne (mrzaz)

**Comment by dbrandesky** [comment]
I think I may have missed something in the installation process. The main page seemed to indicate that I only needed to run +POST_INSTALL.sh; doing so copied the apcupsd.inc file to the appropriate directory, but didn't copy anything to the scripts directory that you referenced. Should I copy all the subdirectories within src to the /usr/local/opnsense directory on the machine as well as running POST_INSTALL?

**Comment by mrzaz** [comment]
> 
> 
> I think I may have missed something in the installation process. The main page seemed to indicate that I only needed to run +POST_INSTALL.sh; doing so copied the apcupsd.inc file to the appropriate directory, but didn't copy anything to the scripts directory that you referenced. Should I copy all the subdirectories within src to the /usr/local/opnsense directory on the machine as well as running POST_INSTALL?

Hello,

Yes, you need to do the following:
1. Execute "pkg install apcupsd" in commandline in opnsense to install latest main program for apcupsd. (login with SSH)
2. Copy the file "apcupsd.inc" to "/usr/local/etc/inc/plugins.inc.d/apcupsd.inc" in case +POST_INSTALL does not work.
3. Copy all files in "src/opnsense/" to "/usr/local/opnsense/".
4. Execute "chmod +x /usr/local/opnsense/scripts/OPNsense/Apcupsd/*.py" to allow script execution.

This is all needed until we have migrated it to the official opnsense / plugin repo that will happen when we feel ready to do it.
Then the plugin installation will take care of all this.

You could then check that you could see Apcupsd in "Services" and that you could configure the service and then start service.
(all depends on how you have your APC UPS connected.  In my case I had a SNMP card but you may have it connected through Serial or USB direct to the machine.  You need to configure what is best for your setup.

You could try the following:

service configd restart
configctl apcupsd getNisStatus

Also do a small test to check if files is Windows CRLF or Unix LF:

If you are running GitHub Client on Windows I would avoid "GitHub Desktop" for Windows as that bastard keeps checking out and converting any line endings from LF to CRLF which will be wrong if you sftp files to OPNSENSE after. BSD does not like CRLF.
I tested out GitExtensions and GitKraken but you have a few tools here https://git-scm.com/download/gui/windows
If you download the zipfile through https://github.com/Gibbon99/apcupsd with "Download ZIP" you should be OK.

**OK**
root@OPNsense:/home/mrzaz # file /usr/local/opnsense/scripts/OPNsense/Apcupsd/getNisStatus.py
/usr/local/opnsense/scripts/OPNsense/Apcupsd/getNisStatus.py: Python script, **ASCII text executable**

**NOK**
root@OPNsense:/home/mrzaz # file /usr/local/opnsense/scripts/OPNsense/Apcupsd/getNisStatus.py
getNisStatus.py: Python script, ASCII text executable, **with CRLF line terminators**

/Danne (mrzaz)

**Comment by dbrandesky** [comment]
This worked, I now see the service in the web UI and can configure the UPS and see its status. Thanks!
